version: '1'
services:
  toolbox_container:
    image: telegram_toolbox
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    command: python3 -u main.py --config config.yaml
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
