services:
  toolbox_container:
    stop_signal: SIGKILL
    image: telegram_toolbox
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - .cache:/root/.cache
    command: python3 -u main.py --config config.yaml
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
